services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: clipvault-app

    ports:
      - "3000:3000"

    environment:
      PORT: 3000
      MONGODB_URI: ${MONGODB_URI:-mongodb://dummy-uri}

    restart: unless-stopped

# Optional local MongoDB service
# Uncomment if you want MongoDB locally instead of Atlas

#  mongo:
#    image: mongo:7
#    container_name: clipvault-mongo
#
#    ports:
#      - "27017:27017"
#
#    volumes:
#      - mongodb_data:/data/db
#
#    restart: unless-stopped

# volumes:
#  mongodb_data: