services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: clipvault-app

    ports:
      - "3000:3000"

    environment:
      PORT: 3000
      MONGODB_URI: ${MONGODB_URI:-mongodb://localhost:27017/clipvault}

    restart: unless-stopped